GET http://localhost:3000/chat?prompt=how are you?

###

GET http://localhost:3000/format-address?address=München Riesstraße 22

###

GET http://localhost:3000/format-address-with-tools?address=München Riesstraße 22

###

GET http://localhost:3000/charging-station-query?query=Find a charging station near munich where i can eat something

###